### ISSUE TITLE
elasticsearch out of memory issue

### ISSUE THREAD

**Issue by GregSilverman** [nlpie/nlp-adapt#23]
Getting heap space error when indexing metampa files (on 3 out of 10), submitted through NLP-TAB web interface:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
[2018-09-11 19:18:26,161][ERROR][rest.action.support      ] failed to send failure response
java.lang.OutOfMemoryError: Java heap space
	at org.elasticsearch.cache.recycler.PageCacheRecycler$1.newInstance(PageCacheRecycler.java:102)
	at org.elasticsearch.cache.recycler.PageCacheRecycler$1.newInstance(PageCacheRecycler.java:99)
	at org.elasticsearch.common.recycler.DequeRecycler.obtain(DequeRecycler.java:53)
	at org.elasticsearch.common.recycler.AbstractRecycler.obtain(AbstractRecycler.java:33)
	at org.elasticsearch.common.recycler.DequeRecycler.obtain(DequeRecycler.java:28)
	at org.elasticsearch.common.recycler.FilterRecycler.obtain(FilterRecycler.java:39)
	at org.elasticsearch.common.recycler.Recyclers$3.obtain(Recyclers.java:119)
	at org.elasticsearch.common.recycler.FilterRecycler.obtain(FilterRecycler.java:39)
	at org.elasticsearch.cache.recycler.PageCacheRecycler.bytePage(PageCacheRecycler.java:150)
	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:453)
	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:466)
	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:60)
	at org.elasticsearch.common.io.stream.ReleasableBytesStreamOutput.<init>(ReleasableBytesStreamOutput.java:36)
	at org.elasticsearch.http.netty.NettyHttpChannel.newBytesOutput(NettyHttpChannel.java:72)
	at org.elasticsearch.rest.RestChannel.bytesOutput(RestChannel.java:93)
	at org.elasticsearch.rest.RestChannel.newBuilder(RestChannel.java:69)
	at org.elasticsearch.rest.RestChannel.newErrorBuilder(RestChannel.java:52)
	at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:123)
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:87)
	at org.elasticsearch.rest.action.support.RestActionListener.onFailure(RestActionListener.java:60)
	at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:51)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:235)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:221)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:785)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:769)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:759)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:283)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2018-09-11 19:18:32,484][WARN ][http.netty               ] [Wicked] Caught exception while handling client http traffic, closing connection [id: 0x7e0d1a82, /127.0.0.1:54350 => /127.0.0.1:9200]
java.lang.OutOfMemoryError: Java heap space
```

**Comment by GregSilverman** [comment]
Increasing heap memory in elasticsearch service startup file in `/etc/init.d` seems to only make this worse, and ultimately ends up pushing the elasticsearch process to top out in CPU usage, ala #22.

**Comment by GregSilverman** [comment]
I have isolated the 2-problem notes from this batch of 10: AL730352 and TW70891.

**Comment by rfinz** [comment]
Not a memory issue - "out of heap space" probably do to with recursion in an annotation and a bug in NLP-TAB. I am closing this issue in favor of an issue on that project.
