### ISSUE TITLE
Submission of metamap_out.zip fails on elastic indexing

### ISSUE THREAD

**Issue by GregSilverman** [nlpie/nlp-adapt#24]
Related to #23, since it was submitted using the same data, but instead through the  api call in `run_metamap.sh`.

Throws the warning (more than likely a red herring):

```
[2018-09-13 18:31:39,102][WARN ][index.translog           ] [Ruckus] [metamap-8011ea0b-1887-4dce-8e18-7fcee7a16c9d][3] failed to delete temp file /var/lib/elasticsearch/elasticsearch/nodes/0/indices/metamap-8011ea0b-1887-4dce-8e18-7fcee7a16c9d/3/translog/translog-1033259967671758268.tlog
java.nio.file.NoSuchFileException: /var/lib/elasticsearch/elasticsearch/nodes/0/indices/metamap-8011ea0b-1887-4dce-8e18-7fcee7a16c9d/3/translog/translog-1033259967671758268.tlog
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
does some indexing and then never completes. And, utilization goes up with only option to delete `/var/lib/elasticsearch/elasticsearch/nodes`.

MetaMap is the only annotator for which this is happening. 

I increased elastic's timeout parameters, as per  [Configuring default HTTP timeouts](https://www.elastic.co/guide/en/watcher/2.1/configuring-default-http-timeouts.html), and am still running with max heap space. If I submit each xmi in the zip file separately with the typesystem file, everything works as expected.

'Fix' is to use smaller xmi output files without gobs of linked annotations. Then, submitting through the api call in shell script behaves as desired.

**Comment by GregSilverman** [comment]
Same as #23
