### ISSUE TITLE
mimic data problems

### ISSUE THREAD

**Issue by GregSilverman** [nlpie/nlp-adapt#9]
Biomedicus issue:

@benknoll-umn @rfinz, I found the following problematic files in the mimic data set running release 1.8.2 of biomedicus:

732645.txt
911139.txt
741251.txt
712849.txt

I'm not going to go through and try and find all the exceptions at this time, since I am now about 1/10th of the way through reading these in. Instead, I'll examine the files. 

The error I am getting is the same for each file (null pointer on number type; snippet below):
```
2018-02-02 15:33:28,070 ERROR [[Procesing Pipeline#1 Thread]::] DocumentProcessorRunner (DocumentProcessorRunner.java:105) - Processing failed on document: 712849
2018-02-02 15:33:28,070 ERROR [[Procesing Pipeline#1 Thread]::] DocumentProcessorUimaAdapter (DocumentProcessorUimaAdapter.java:115) - error while processing document
2018-02-02 15:33:28,070 ERROR [[Procesing Pipeline#1 Thread]::] PrimitiveAnalysisEngine_impl (PrimitiveAnalysisEngine_impl.java:417) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:116) ~[biomedicus-uima-1.8.2.jar:?]

...

2018-02-02 15:33:28,082 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2345) - The container Default BioMedICUS Pipeline returned the following error message: null (Thread Name: [Procesing Pipeline#1 Thread]::)
2018-02-02 15:33:28,083 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2498) - Thread: [Procesing Pipeline#1 Thread]::, message: null
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:116) ~[biomedicus-uima-1.8.2.jar:?]
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]
Caused by: edu.umn.biomedicus.exc.BiomedicusException: java.lang.NullPointerException: numberType
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:106) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:113) ~[biomedicus-uima-1.8.2.jar:?]
	... 10 more
Caused by: java.lang.NullPointerException: numberType
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228) ~[guava-19.0.jar:?]
	at edu.umn.biomedicus.measures.ImmutableNumber$Builder.numberType(ImmutableNumber.java:235) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.measures.NumberRecognizer.labelSeq(NumberRecognizer.java:126) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.measures.NumberRecognizer.extract(NumberRecognizer.java:101) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.measures.NumberRecognizer.process(NumberRecognizer.java:76) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.lambda$processDocument$0(DocumentProcessorRunner.java:101) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.framework.BiomedicusScopes$Context.call(BiomedicusScopes.java:134) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:100) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:113) ~[biomedicus-uima-1.8.2.jar:?]
	... 10 more
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:116)
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575)
Caused by: edu.umn.biomedicus.exc.BiomedicusException: java.lang.NullPointerException: numberType
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:106)
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:113)
	... 10 more
Caused by: java.lang.NullPointerException: numberType
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at edu.umn.biomedicus.measures.ImmutableNumber$Builder.numberType(ImmutableNumber.java:235)
	at edu.umn.biomedicus.measures.NumberRecognizer.labelSeq(NumberRecognizer.java:126)
	at edu.umn.biomedicus.measures.NumberRecognizer.extract(NumberRecognizer.java:101)
	at edu.umn.biomedicus.measures.NumberRecognizer.process(NumberRecognizer.java:76)
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.lambda$processDocument$0(DocumentProcessorRunner.java:101)
	at edu.umn.biomedicus.framework.BiomedicusScopes$Context.call(BiomedicusScopes.java:134)
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:100)
	... 11 more
2018-02-02 15:34:08,015 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingContainer_Impl (ProcessingContainer_Impl.java:786) - The CPM stopped because the configured error threshold 0 was exceeded. (Thread Name: [Procesing Pipeline#1 Thread]::) Component Name: Default BioMedICUS Pipeline
2018-02-02 15:34:08,017 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2345) - The CPM is terminating. The current component is Default BioMedICUS Pipeline. (Thread Name: [Procesing Pipeline#1 Thread]::)
2018-02-02 15:34:08,017 WARN  [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2345) - The CPM cannot be stopped by force. The current container is Default BioMedICUS Pipeline. (Thread Name: [Procesing Pipeline#1 Thread]::) Reason: The CAS processor Default BioMedICUS Pipeline is configured to stop the CPM when excessive errors are encountered.  (Thread Name: [Procesing Pipeline#1 Thread]::)
2018-02-02 15:34:08,018 INFO  [[CollectionReader Thread]::] FilesInDirectoryReader (FilesInDirectoryReader.java:179) - Reading file: 714545.txt
2018-02-02 15:34:08,018 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2498) - Thread: [Procesing Pipeline#1 Thread]::, message:
org.apache.uima.collection.base_cpm.AbortCPMException:
	at org.apache.uima.collection.impl.cpm.container.ProcessingContainer_Impl.incrementCasProcessorErrors(ProcessingContainer_Impl.java:795) ~[uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:1037) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]
```

Metamap:

Metamap is crashing on a few files - might be cause by a similar number recognition issue.
A few examples:

1761.txt
1806825.txt
1913973.txt

**Comment by GregSilverman** [comment]
More on biomediucs error: Grepped the above files for non-printable ascii/control characters with null results. Not sure what else to check on these files and why they are throwing errors. NB: I did try setting the logging to debug/trace, but was unable to get more detail on the error being thrown.

A couple questions:

1. Would it be possible to modify the pipeline to instead of crashing when hitting this particular error that it would just log/flag the file as bad and continue processing (instead of terminating)?
2. Is it possible to give more detail as to what is throwing the error?

These results confirm those discovered by @rfinz, with the addition of the particular file names throwing the error.

Also note that the above files that throw exceptions in biomedicus 1.8.2 all run fine in the ctakes-4.0.0 default pipeline.

**Comment by GregSilverman** [comment]
Reproduced @rfinz issue wrt non-printable ascii characters throwing error when processing data using ctakes. (isolated files using `grep -r '[^[:print:]]' *` and `grep -r '[^[:print:][:blank:]]' *`.)

Fixed using command `sed -i -e 's/[^[:print:]]//' *` 

To recursively run sed across a directory tree, see [recursively search and replace](https://stackoverflow.com/questions/9704020/recursive-search-and-replace-in-text-files-on-mac-and-linux).

**Comment by benknoll-umn** [comment]
These errors may be due to a bug in the number recognizer, I will check on what is causing them.

**Comment by benknoll-umn** [comment]
It's definitely being caused by issues in the number recognizer, for example a string of numbers like "136/66/7.2/-27/.3", the number being followed by a slash and then '-' causes it to break. I'm going to move fraction recognition out of the combined number detector and create a separate detector for it.

**Comment by GregSilverman** [comment]
@benknoll-umn, @rfinz: applied biomedicus hot fix 1.8.3... processing on FileSystemCollectionReader now hangs on 919962.txt. Tested multiple times. No funky looking stuff in file (as a test removed all forward slashes, to no avail...).

**Comment by benknoll-umn** [comment]
It failed on 983849.txt, located the cause of this one, it's a bad one – introduced in the 1.8.3 fixes.

**Comment by benknoll-umn** [comment]
Since I am doing a hotfix anyways I will also fix the issue that broke JCasGen for Ray

**Comment by GregSilverman** [comment]
biomedicus 1.8.4 resolved issue found on 983849.txt.

**Comment by rfinz** [comment]
Metamap crashes on 10283.txt  due to two floating '.'

We should create a place to track problematic input types. Candidates:

+ unprintable characters
+ certain unicode code points
+ malformed fractions
+ floating '.'

**Comment by GregSilverman** [comment]
This seems to be the most appropriate place to track issues with the mimic data set. 

We will be adding a relevant section (viz., "Known Issues") to the NLP-IE VM usage instructions (along with script examples for correcting them).

**Comment by GregSilverman** [comment]
MetaMap errored on floating/stray '.' (file 10283.txt). 

<img width="754" alt="screen shot 2018-02-12 at 10 21 57 am" src="https://user-images.githubusercontent.com/1007034/36107620-46340a24-0fe0-11e8-9a01-cb6ca1e54500.png">

**Comment by GregSilverman** [comment]
@rfinz, the command to search for floating '.' did not work. It needs to search across multiple lines for a blank line followed by a line with only a period. Standard grep does not easily support this operation, but pcregrep does. Unfortunately, this will have to be installed on the VM using 'apt install,' since it is not standard. Please make sure you install this in the latest VM build.

**Comment by GregSilverman** [comment]
@rfinz, this is the latest and greatest script for identifying known issues. I also added line numbers for ease of identification in offending files.

```
#!/bin/bash

echo "Preprocess data for annotator consumption"

echo ""
echo "These files have ill-formed fractions:"
grep -Pnr -- '\d+/\d+-' *

echo ""
echo "These files have non-printable ASCII characters:"
grep -nr '[^[:print:]]' *

echo ""
echo "These files have unicode tabs:"
grep -nr $'\t' *

echo ""
echo "These files have floating periods:"
pcregrep -Mnr  '^$.*\n^\.' *.txt

```

**Comment by rmcewan** [comment]
@GregSilverman: can the grep commands be wrapped in a logical structure to provide an explicit message when no matches are found? It's a small point, but provides better feedback to the user.

**Comment by GregSilverman** [comment]
@rmcewan, yes, something like:

```
if ! grep "regex" "filepath"; then
    echo "no match" >&2
fi
```

should do it. I will modify and test.

**Comment by GregSilverman** [comment]
Done (since the directory structure is flat, I removed the `-r` switch to search recursively):

```
echo "Preprocess data for annotator consumption"

echo ""
echo "Looking for files with ill-formed fractions:"
grep -Pn -- '\d+/\d+-' * || echo "no matches found for ill-formed fractions!"


echo ""
echo "Looking for files with non-printable ASCII characters:"
grep -n '[^[:print:]]' * || echo "no matches foundfor non-printable ASCII characters!"


echo ""
echo "Looking for files with unicode tabs:"
grep -n $'\t' * || echo "no matches found for unicode tabs!"


echo ""
echo "Looking for files with floating periods:"
pcregrep -Mn  '^$.*\n^\.' * || echo "no matches found for floating periods!"

```

**Comment by rmcewan** [comment]
Nice, thanks Greg!

**Comment by rfinz** [comment]
![virtualbox_nlp-ie_21_02_2018_13_07_58](https://user-images.githubusercontent.com/1740357/36508075-330b8254-1721-11e8-85ae-2af75f634a88.png)

MetaMap does not always consider a line break to be whitespace. Needs investigation.

Is this worth fretting over? The proper concepts were matched.

**Comment by GregSilverman** [comment]
@rfinz, is this a mimic data problem? You may wish to open a separate issue for each specific annotator system.

**Comment by GregSilverman** [comment]
I am going to close this issue, since I think we have flushed out all the problems with the mimic data set.

**Comment by rfinz** [comment]
Probably would have called it a mimic data problem because it might have to do with the line endings, but I'm fine with leaving this closed.

**Comment by GregSilverman** [comment]
I will investigate. Is it LF or CR returns or both LF & CR? Do you have a specific file where this happens or at least a candidate out of a batch of files?

**Comment by GregSilverman** [comment]
@rfinz, I think this is already addressed with non-printable ASCII characters. We could just add a note in the instructions about the potential effect of data in NLP-Tab.
